apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-api-deployment
spec:
  selector:
    matchLabels:
      app: workload-api
  template:
    metadata:
      labels:
        app: workload-api
    spec:
      containers:
      - name: workload-api
        image: ghcr.io/aau-p9s/workload-api:latest
        environment:
          WORKLOAD_PORT: 8123
        ports:
        - containerPort: 8123

        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1024Mi"
            cpu: "2000m"

