apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-deployment
spec:
  selector:
    matchLabels:
      app: workload
  template:
    metadata:
      labels:
        app: workload
    spec:
      containers:
      - name: workload
        image: ghcr.io/aau-p9s/workload:latest
        ports:
        - containerPort: 8000

        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1024Mi"
            cpu: "2000m"

