apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-generator
  template:
    metadata:
      labels:
        app: workload-generator
    spec:
      containers:
        - name: workload-generator
          image: ghcr.io/aau-p9s/workload-generator:latest
          env:
            - name: GENERATOR_API_ADDR
              value: workload-api
            - name: GENERATOR_API_PORT
              value: "8082"
            - name: GENERATOR_ADDR
              value: 0.0.0.0
            - name: GENERATOR_PORT
              value: "8083"
          ports:
            - containerPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: workload-generator
spec:
  type: NodePort
  selector:
    app: workload-generator
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
      nodePort: 30083

